config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: {scope: :ingredient_id}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @ingredients = Ingredient.all
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :remote_photo_url)
    # :remote_photo_url pour pouvoir demander un URL pour
    # un cocktail
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :destroy]

# I shouldn't need this!
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)

    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      puts "-----------------------------"
      puts "DIDNT WORK ------------------"
      puts "-----------------------------"
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h2>Modifying <%= @cocktail.name %></h2>

<h3>Currently in this cocktail :</h3>
<% @cocktail.doses.each do |dose| %>
  <p><%= dose.description %> <%= dose.ingredient.name %></p>
  <br>
<% end %>

<%= render 'shared/form', cocktail: @cocktail, dose: @dose %>

app/views/cocktails/index.html.erb
<h1 class="text-center">CoffeeCocktails</h1>


<div class="container-fluid">
  <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-4">
          <% unless cocktail.photo.file.nil? %>
            <%= cl_image_tag cocktail.photo, height: 200, width: 300, crop: :fill %>
            <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          <% else %>
            <%= cl_image_tag("klkt9dq4nrnwny4wco6b",
              width: 300, height: 200, crop: :fill, :transformation => {:effect => "blur:500", :opacity => 50}) %>
              <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create your cocktail</h1>

<%= render 'shared/form', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %> details</h1>

<br>
<% unless @cocktail.photo.file.nil? %>
  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<% else %>
  <p>Add a picture!</p>
<% end %>
<% if @cocktail.doses.length > 0 %>
  <h2>For this cocktail you will need :</h2>
  <% @cocktail.doses.each do |dose| %>
    <li><%= dose.description %> <%= dose.ingredient.name %></li>
  <% end %>
<% else %>
  <p>No Ingredient yet, add some!</p>
<% end %>
<br>
<br>
<h2>Not the right cocktail name? <%= link_to "Modify!", edit_cocktail_path(@cocktail) %></h2>
<br>
<h3>Something's missing?<br>Add an ingredient</h3>

<%= render 'shared/dose_form', cocktail: @cocktail %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktailFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  <script type="text/javascript" data-turbolinks-eval=false>
  console.log("I'm only run once on the initial page load");
</script>
  </body>
</html>

app/views/shared/_dose_form.html.erb
<%=  "-----------------------------" %>
<!-- Need to precise the method! -->

<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%#= f.association :ingredient, input_html: { class: 'select2' } %>
  <%= select_tag :ingredient,options_from_collection_for_select(@ingredients, :id, :name, "1") %>
  <%#= f.association select_tag :ingredient, options_for_select(Ingredient.all.map {|x| [x.name, x.id]}), class: "select2" %>

  <%#= select_tag :ingredient, options_from_collection_for_select(Ingredient.all,
    :name, :name) %>
  <%#= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.button :submit, "Add dose", class: "btn btn-success" %>
<% end %>





<!-- NE PAS TOUCHER IL MARCH!!!!!!!!!!!!!! -->
<%#= simple_form_for ([@cocktail, @dose]), method: :post do |f| %>
        <%#= f.association :ingredient, class: 'select2' %>
        <%#= f.input :description %>
        <%#= f.button :submit, class: "btn btn-primary"%>
      <%# end %>

app/views/shared/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :remote_photo_url, label: "OR photo URL" %>
  <!-- pour demander un URL comme photo -->
  <%= f.submit 'Submit!' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon row">
  <div class=".navbar-lewagon .navbar-brand">
    <%= link_to (image_tag("logo-cocktail.png", alt: "Cocktails&Dreams", width: 60, class:"avatar")), root_path %>
  </div>
  <h3>Cocktails&Dreams</h3>
  <h2><%= link_to "Add your cocktail", new_cocktail_url %></h2>

</div>